// Automatically generated by MockGen. DO NOT EDIT!
// Source: model/model.go

package mocks

import (
	data "data"
	gomock "github.com/golang/mock/gomock"
)

// Mock of Model interface
type MockModel struct {
	ctrl     *gomock.Controller
	recorder *_MockModelRecorder
}

// Recorder for MockModel (not exported)
type _MockModelRecorder struct {
	mock *MockModel
}

func NewMockModel(ctrl *gomock.Controller) *MockModel {
	mock := &MockModel{ctrl: ctrl}
	mock.recorder = &_MockModelRecorder{mock}
	return mock
}

func (_m *MockModel) EXPECT() *_MockModelRecorder {
	return _m.recorder
}

func (_m *MockModel) Run() error {
	ret := _m.ctrl.Call(_m, "Run")
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockModelRecorder) Run() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Run")
}

func (_m *MockModel) CreateGame(word string) data.Game {
	ret := _m.ctrl.Call(_m, "CreateGame", word)
	ret0, _ := ret[0].(data.Game)
	return ret0
}

func (_mr *_MockModelRecorder) CreateGame(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "CreateGame", arg0)
}

func (_m *MockModel) UpdateGame(id string, game data.Game) error {
	ret := _m.ctrl.Call(_m, "UpdateGame", id, game)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockModelRecorder) UpdateGame(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "UpdateGame", arg0, arg1)
}

func (_m *MockModel) GetGame(id string) (data.Game, error) {
	ret := _m.ctrl.Call(_m, "GetGame", id)
	ret0, _ := ret[0].(data.Game)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockModelRecorder) GetGame(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "GetGame", arg0)
}

func (_m *MockModel) GetGamesInfo() []data.GameInfo {
	ret := _m.ctrl.Call(_m, "GetGamesInfo")
	ret0, _ := ret[0].([]data.GameInfo)
	return ret0
}

func (_mr *_MockModelRecorder) GetGamesInfo() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "GetGamesInfo")
}
