// Automatically generated by MockGen. DO NOT EDIT!
// Source: word/word.go

package mocks

import (
	gomock "github.com/golang/mock/gomock"
)

// Mock of Words interface
type MockWords struct {
	ctrl     *gomock.Controller
	recorder *_MockWordsRecorder
}

// Recorder for MockWords (not exported)
type _MockWordsRecorder struct {
	mock *MockWords
}

func NewMockWords(ctrl *gomock.Controller) *MockWords {
	mock := &MockWords{ctrl: ctrl}
	mock.recorder = &_MockWordsRecorder{mock}
	return mock
}

func (_m *MockWords) EXPECT() *_MockWordsRecorder {
	return _m.recorder
}

func (_m *MockWords) GetWord() string {
	ret := _m.ctrl.Call(_m, "GetWord")
	ret0, _ := ret[0].(string)
	return ret0
}

func (_mr *_MockWordsRecorder) GetWord() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "GetWord")
}
